//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kephas.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PipelinesStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PipelinesStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kephas.Resources.PipelinesStrings", typeof(PipelinesStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoked pipeline behavior ({0}/{1}/{2}/{3})....
        /// </summary>
        internal static string Pipeline_ProcessAsync_InvokedBehavior_Message {
            get {
                return ResourceManager.GetString("Pipeline_ProcessAsync_InvokedBehavior_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoked pipeline operation ({0}/{1}/{2})..
        /// </summary>
        internal static string Pipeline_ProcessAsync_InvokedOperation_Message {
            get {
                return ResourceManager.GetString("Pipeline_ProcessAsync_InvokedOperation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking pipeline behavior ({0}/{1}/{2}/{3})....
        /// </summary>
        internal static string Pipeline_ProcessAsync_InvokingBehavior_Message {
            get {
                return ResourceManager.GetString("Pipeline_ProcessAsync_InvokingBehavior_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking pipeline operation ({0}/{1}/{2})....
        /// </summary>
        internal static string Pipeline_ProcessAsync_InvokingOperation_Message {
            get {
                return ResourceManager.GetString("Pipeline_ProcessAsync_InvokingOperation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumeration provided a null behavior..
        /// </summary>
        internal static string Pipeline_ProcessAsync_NullBehavior_Exception {
            get {
                return ResourceManager.GetString("Pipeline_ProcessAsync_NullBehavior_Exception", resourceCulture);
            }
        }
    }
}
