//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kephas.Injection.Lite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LiteStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LiteStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kephas.Injection.Lite.Resources.LiteStrings", typeof(LiteStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contract type is not set..
        /// </summary>
        internal static string LiteRegistrationBuilder_Build_ContractTypeNotSet {
            get {
                return ResourceManager.GetString("LiteRegistrationBuilder_Build_ContractTypeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The implementation type {0} must be also a generic type definition for contract {1}..
        /// </summary>
        internal static string LiteRegistrationBuilder_EnsureContractTypeMatchesImplementationType_ImplementationTypeMustBeGenericTypeDefinition {
            get {
                return ResourceManager.GetString("LiteRegistrationBuilder_EnsureContractTypeMatchesImplementationType_Implementatio" +
                        "nTypeMustBeGenericTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The implementation type {0} must not be a generic type definition for contract {1}..
        /// </summary>
        internal static string LiteRegistrationBuilder_EnsureContractTypeMatchesImplementationType_ImplementationTypeMustNotBeGenericTypeDefinition {
            get {
                return ResourceManager.GetString("LiteRegistrationBuilder_EnsureContractTypeMatchesImplementationType_Implementatio" +
                        "nTypeMustNotBeGenericTypeDefinition", resourceCulture);
            }
        }
    }
}
