//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kephas.Messaging.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kephas.Messaging.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content message may be null only for replies. Use ReplyTo() before setting the content if you intend to create a reply..
        /// </summary>
        public static string BrokeredMessageBuilder_ContentNullWhenNotReply_Exception {
            get {
                return ResourceManager.GetString("BrokeredMessageBuilder_ContentNullWhenNotReply_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify a negative timeout value..
        /// </summary>
        public static string BrokeredMessageBuilder_NonNegativeTimeout_Exception {
            get {
                return ResourceManager.GetString("BrokeredMessageBuilder_NonNegativeTimeout_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reply processing was canceled..
        /// </summary>
        public static string BrokeredMessageHandler_ProcessAndReply_Canceled {
            get {
                return ResourceManager.GetString("BrokeredMessageHandler_ProcessAndReply_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reply processing is faulted..
        /// </summary>
        public static string BrokeredMessageHandler_ProcessAndReply_Exception {
            get {
                return ResourceManager.GetString("BrokeredMessageHandler_ProcessAndReply_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response processing was canceled..
        /// </summary>
        public static string BrokeredMessageHandler_ProcessAndRespond_Canceled {
            get {
                return ResourceManager.GetString("BrokeredMessageHandler_ProcessAndRespond_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response processing is faulted..
        /// </summary>
        public static string BrokeredMessageHandler_ProcessAndRespond_Exception {
            get {
                return ResourceManager.GetString("BrokeredMessageHandler_ProcessAndRespond_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one-way processing was canceled..
        /// </summary>
        public static string BrokeredMessageHandler_ProcessOneWay_Canceled {
            get {
                return ResourceManager.GetString("BrokeredMessageHandler_ProcessOneWay_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one-way processing is faulted..
        /// </summary>
        public static string BrokeredMessageHandler_ProcessOneWay_Exception {
            get {
                return ResourceManager.GetString("BrokeredMessageHandler_ProcessOneWay_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no message router to handle messages without recipients..
        /// </summary>
        public static string DefaultMessageBroker_CannotHandleMessagesWithoutRecipients_Exception {
            get {
                return ResourceManager.GetString("DefaultMessageBroker_CannotHandleMessagesWithoutRecipients_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred while sending message &apos;{0}&apos;..
        /// </summary>
        public static string DefaultMessageBroker_ErrorsOccurredWhileSending_Exception {
            get {
                return ResourceManager.GetString("DefaultMessageBroker_ErrorsOccurredWhileSending_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send message to the following recipients: {0}. There is no message router to handle them..
        /// </summary>
        public static string DefaultMessageBroker_NoMessageRoutersCanHandleRecipients_Exception {
            get {
                return ResourceManager.GetString("DefaultMessageBroker_NoMessageRoutersCanHandleRecipients_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple handlers found for the &apos;{0}&apos; message type: {1}. Please disambiguate by using the [OverridePriority] attribute on them..
        /// </summary>
        public static string DefaultMessageProcessor_AmbiguousHandler_Exception {
            get {
                return ResourceManager.GetString("DefaultMessageProcessor_AmbiguousHandler_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a handler for the &apos;{0}&apos; message type..
        /// </summary>
        public static string DefaultMessageProcessor_MissingHandler_Exception {
            get {
                return ResourceManager.GetString("DefaultMessageProcessor_MissingHandler_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message is not set in the message adapter..
        /// </summary>
        public static string MessageAdapter_MessageNotSet_Exception {
            get {
                return ResourceManager.GetString("MessageAdapter_MessageNotSet_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not enqueue brokered message (#{0}, {1}) timeout: {2}..
        /// </summary>
        public static string MessageBrokerBase_LogOnEnqueue_NotAddedError {
            get {
                return ResourceManager.GetString("MessageBrokerBase_LogOnEnqueue_NotAddedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue brokered message (#{0}, {1}) timeout: {2}..
        /// </summary>
        public static string MessageBrokerBase_LogOnEnqueue_Success {
            get {
                return ResourceManager.GetString("MessageBrokerBase_LogOnEnqueue_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received a reply message without the {0} being set. Content: {1}..
        /// </summary>
        public static string MessageBrokerBase_MissingReplyToMessageId_Exception {
            get {
                return ResourceManager.GetString("MessageBrokerBase_MissingReplyToMessageId_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received a reply to &apos;{0}&apos; for which the corresponding original message was not found. Possible cause: a timeout may have had interrupted the communication. Content: {1}..
        /// </summary>
        public static string MessageBrokerBase_ReplyToMessageNotFound_Exception {
            get {
                return ResourceManager.GetString("MessageBrokerBase_ReplyToMessageNotFound_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum alloted time of {0} expired for {1}..
        /// </summary>
        public static string MessageBrokerBase_Timeout_Exception {
            get {
                return ResourceManager.GetString("MessageBrokerBase_Timeout_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message to process must be of type &apos;{0}&apos;..
        /// </summary>
        public static string MessageHandler_BadMessageType_Exception {
            get {
                return ResourceManager.GetString("MessageHandler_BadMessageType_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the one-way request &apos;{0}&apos;. Please check the exception details for more information..
        /// </summary>
        public static string MessageRouterBase_ProcessOneWay_Exception {
            get {
                return ResourceManager.GetString("MessageRouterBase_ProcessOneWay_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending the reply to &apos;{0}&apos;. Please check the exception details for more information..
        /// </summary>
        public static string MessageRouterBase_Reply_Exception {
            get {
                return ResourceManager.GetString("MessageRouterBase_Reply_Exception", resourceCulture);
            }
        }
    }
}
