//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kephas.Messaging.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kephas.Messaging.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content message may not be a Delegate type: &apos;{0}&apos;..
        /// </summary>
        public static string BrokeredMessage_ContentCannotBeDelegate_Exception {
            get {
                return ResourceManager.GetString("BrokeredMessage_ContentCannotBeDelegate_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content message may be null only for replies: &apos;{0}&apos;. Use {1}() before setting the content if you intend to create a reply..
        /// </summary>
        public static string BrokeredMessage_ContentNullWhenNotReply_Exception {
            get {
                return ResourceManager.GetString("BrokeredMessage_ContentNullWhenNotReply_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One and only one recipient required for requests awaiting replies: &apos;{0}&apos;..
        /// </summary>
        public static string BrokeredMessage_OneRecipient_Required_Exception {
            get {
                return ResourceManager.GetString("BrokeredMessage_OneRecipient_Required_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide at least one recipient if the message is not an event: &apos;{0}&apos;..
        /// </summary>
        public static string BrokeredMessage_RecipientRequired_Exception {
            get {
                return ResourceManager.GetString("BrokeredMessage_RecipientRequired_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reply processing was canceled..
        /// </summary>
        public static string BrokeredMessageHandler_ProcessAndReply_Canceled {
            get {
                return ResourceManager.GetString("BrokeredMessageHandler_ProcessAndReply_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reply processing is faulted..
        /// </summary>
        public static string BrokeredMessageHandler_ProcessAndReply_Exception {
            get {
                return ResourceManager.GetString("BrokeredMessageHandler_ProcessAndReply_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response processing was canceled..
        /// </summary>
        public static string BrokeredMessageHandler_ProcessAndRespond_Canceled {
            get {
                return ResourceManager.GetString("BrokeredMessageHandler_ProcessAndRespond_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response processing is faulted..
        /// </summary>
        public static string BrokeredMessageHandler_ProcessAndRespond_Exception {
            get {
                return ResourceManager.GetString("BrokeredMessageHandler_ProcessAndRespond_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one-way processing was canceled..
        /// </summary>
        public static string BrokeredMessageHandler_ProcessOneWay_Canceled {
            get {
                return ResourceManager.GetString("BrokeredMessageHandler_ProcessOneWay_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one-way processing is faulted..
        /// </summary>
        public static string BrokeredMessageHandler_ProcessOneWay_Exception {
            get {
                return ResourceManager.GetString("BrokeredMessageHandler_ProcessOneWay_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; receiver match provider does not implement &apos;{1}&apos;..
        /// </summary>
        public static string DefaultMessageBroker_BadReceiverMatchProviderType_Exception {
            get {
                return ResourceManager.GetString("DefaultMessageBroker_BadReceiverMatchProviderType_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no message router to handle messages without recipients..
        /// </summary>
        public static string DefaultMessageBroker_CannotHandleMessagesWithoutRecipients_Exception {
            get {
                return ResourceManager.GetString("DefaultMessageBroker_CannotHandleMessagesWithoutRecipients_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred while redirecting reply &apos;{0}&apos;..
        /// </summary>
        public static string DefaultMessageBroker_ErrorsOccurredWhileRedirecting_Exception {
            get {
                return ResourceManager.GetString("DefaultMessageBroker_ErrorsOccurredWhileRedirecting_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred while sending message &apos;{0}&apos;..
        /// </summary>
        public static string DefaultMessageBroker_ErrorsOccurredWhileSending_Exception {
            get {
                return ResourceManager.GetString("DefaultMessageBroker_ErrorsOccurredWhileSending_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not enqueue brokered message (#{0}, {1}) timeout: {2}..
        /// </summary>
        public static string DefaultMessageBroker_LogOnEnqueue_NotAddedError {
            get {
                return ResourceManager.GetString("DefaultMessageBroker_LogOnEnqueue_NotAddedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue brokered message (#{0}, {1}) timeout: {2}..
        /// </summary>
        public static string DefaultMessageBroker_LogOnEnqueue_Success {
            get {
                return ResourceManager.GetString("DefaultMessageBroker_LogOnEnqueue_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received a reply message without the {0} being set (&apos;{0}&apos;)..
        /// </summary>
        public static string DefaultMessageBroker_MissingReplyToMessageId_Exception {
            get {
                return ResourceManager.GetString("DefaultMessageBroker_MissingReplyToMessageId_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send message to the following recipients: {0}. There is no message router to handle them..
        /// </summary>
        public static string DefaultMessageBroker_NoMessageRoutersCanHandleRecipients_Exception {
            get {
                return ResourceManager.GetString("DefaultMessageBroker_NoMessageRoutersCanHandleRecipients_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply &apos;{0}&apos;, which has no corresponding request. Possible cause: a timeout may have had interrupted the communication..
        /// </summary>
        public static string DefaultMessageBroker_ReplyToMessageNotFound_Exception {
            get {
                return ResourceManager.GetString("DefaultMessageBroker_ReplyToMessageNotFound_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum allotted time of {0} expired for {1}..
        /// </summary>
        public static string DefaultMessageBroker_Timeout_Exception {
            get {
                return ResourceManager.GetString("DefaultMessageBroker_Timeout_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple handlers found for the &apos;{0}&apos; message type: {1}. Please disambiguate by using the [OverridePriority] attribute on them..
        /// </summary>
        public static string DefaultMessageProcessor_AmbiguousHandler_Exception {
            get {
                return ResourceManager.GetString("DefaultMessageProcessor_AmbiguousHandler_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a handler for the &apos;{0}&apos; message type..
        /// </summary>
        public static string DefaultMessageProcessor_MissingHandler_Exception {
            get {
                return ResourceManager.GetString("DefaultMessageProcessor_MissingHandler_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify a negative timeout value..
        /// </summary>
        public static string DispatchingContext_NonNegativeTimeout_Exception {
            get {
                return ResourceManager.GetString("DispatchingContext_NonNegativeTimeout_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event hub &apos;{0}&apos; must implement the &apos;{1}&apos; interface to use the messaging extensions..
        /// </summary>
        public static string EventHubExtensions_MissingMessagingEventHubImplementation {
            get {
                return ResourceManager.GetString("EventHubExtensions_MissingMessagingEventHubImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected only replies in the output queue, instead received &apos;{0}&apos;..
        /// </summary>
        public static string InProcessMessageRouter_UnexpectedMessageInOutputQueue {
            get {
                return ResourceManager.GetString("InProcessMessageRouter_UnexpectedMessageInOutputQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message is not set in the message adapter..
        /// </summary>
        public static string MessageAdapter_MessageNotSet_Exception {
            get {
                return ResourceManager.GetString("MessageAdapter_MessageNotSet_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message to process must be of type &apos;{0}&apos;, received &apos;{1}&apos;..
        /// </summary>
        public static string MessageHandler_BadMessageType_Exception {
            get {
                return ResourceManager.GetString("MessageHandler_BadMessageType_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred while asynchronously dispatching &apos;{0}&apos;..
        /// </summary>
        public static string MessageRouterBase_ErrorsOccurredWhileDispatching_Exception {
            get {
                return ResourceManager.GetString("MessageRouterBase_ErrorsOccurredWhileDispatching_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred while asynchronously processing one way message &apos;{0}&apos;..
        /// </summary>
        public static string MessageRouterBase_ErrorsOccurredWhileProcessingOneWay_Exception {
            get {
                return ResourceManager.GetString("MessageRouterBase_ErrorsOccurredWhileProcessingOneWay_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred while routing message &apos;{0}&apos;..
        /// </summary>
        public static string MessageRouterBase_ErrorsOccurredWhileRoutingMessage_Exception {
            get {
                return ResourceManager.GetString("MessageRouterBase_ErrorsOccurredWhileRoutingMessage_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the one-way request &apos;{0}&apos;. Please check the exception details for more information..
        /// </summary>
        public static string MessageRouterBase_ProcessOneWay_Exception {
            get {
                return ResourceManager.GetString("MessageRouterBase_ProcessOneWay_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending the reply to &apos;{0}&apos;. Please check the exception details for more information..
        /// </summary>
        public static string MessageRouterBase_Reply_Exception {
            get {
                return ResourceManager.GetString("MessageRouterBase_Reply_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot handle multiple replies for {0}..
        /// </summary>
        public static string MessageRouterBase_RouteInputAsync_CannotHandleMultipleReplies {
            get {
                return ResourceManager.GetString("MessageRouterBase_RouteInputAsync_CannotHandleMultipleReplies", resourceCulture);
            }
        }
    }
}
